import { HashtagCategory } from '../../models/hashtag-category';
import { Hashtag } from '~/app/models/hashtag';

export const HASHTAGS: HashtagCategory[] = [
    {
        id: 0,
        title: "results_category_niche_hashtags",
        tags: [
            new Hashtag({ title: "#b***e" }),
            new Hashtag({ title: "#urb***" }),
            new Hashtag({ title: "#***art" }),
            new Hashtag({ title: "#street" }),
            new Hashtag({ title: "#evening" }),
            new Hashtag({ title: "#home" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#colorful" }),
            new Hashtag({ title: "#illustration" }),
            new Hashtag({ title: "#home" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#evening" }),
            new Hashtag({ title: "#home" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#colorful" }),
            new Hashtag({ title: "#illustration" }),
            new Hashtag({ title: "#home" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#colorful" }),
            new Hashtag({ title: "#illustration" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#world" }),
        ],
        recommendedAmount: 2,
    },
    {
        id: 1,
        title: "results_category_generic_hashtags",
        tags: [
            new Hashtag({ title: "#b***e" }),
            new Hashtag({ title: "#urb***" }),
            new Hashtag({ title: "#***art" }),
            new Hashtag({ title: "#street" }),
            new Hashtag({ title: "#evening" }),
            new Hashtag({ title: "#home" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#colorful" }),
            new Hashtag({ title: "#urban" }),
            new Hashtag({ title: "#illustration" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#world" }),
        ],
        recommendedAmount: 4,
    },
    {
        id: 2,
        title: "results_category_upcoming_hashtags",
        tags: [
            new Hashtag({ title: "#b***e" }),
            new Hashtag({ title: "#urb***" }),
            new Hashtag({ title: "#***art" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#colorful" }),
            new Hashtag({ title: "#urban" }),
            new Hashtag({ title: "#illustration" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#world" }),
        ],
        recommendedAmount: 5,
    },
    {
        id: 3,
        title: "results_category_location_based_hashtags",
        tags: [
            new Hashtag({ title: "#b***e" }),
            new Hashtag({ title: "#urb***" }),
            new Hashtag({ title: "#street" }),
            new Hashtag({ title: "#urban" }),
            new Hashtag({ title: "#illustration" }),
            new Hashtag({ title: "#lights" }),
            new Hashtag({ title: "#town" }),
            new Hashtag({ title: "#world" }),
        ],
        recommendedAmount: 6,
    },
];